#
# Create by Le Trong on 03/Mar/2019
#
steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build deployable image (commit tag)"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bm-account-service:$SHORT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push deployable image (commit tag)"
    args: ["push", "gcr.io/$PROJECT_ID/bm-account-service:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    id: "Build deployable image (latest tag)"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/bm-account-service:latest", "."]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push deployable image (latest tag)"
    args: ["push", "gcr.io/$PROJECT_ID/bm-account-service:latest"]

  - name: "gcr.io/cloud-builders/kubectl"
    id: 'Apply Kubectl configuration'
    args:
      - "set"
      - "image"
      - "deployment/masonjar-backend-deployment"
      - "masonjar-backend-container=gcr.io/$PROJECT_ID/bm-account-service:latest"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=northamerica-northeast1"
      - "CLOUDSDK_CONTAINER_CLUSTER=masonjar-service-cluster"

images:
  - "gcr.io/$PROJECT_ID/bm-account-service:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/bm-account-service:latest"
